### ISSUE TITLE
Please review website draft

### ISSUE THREAD

**Issue by dhuppenkothen** [AstroHackWeek/2017#1]
Hi all, I'd be very grateful if you could all have a quick look at the draft of the Astro Hack Week 2017 website and let me know if anything needs changing (either content-, layout- or style-wise).

**Comment by davidwhogg** [comment]
Can you give me a link?

**Comment by dhuppenkothen** [comment]
http://astrohackweek.org/2017/

**Comment by kbarbary** [comment]
Just a few small edits: #2

**Comment by davidwhogg** [comment]
I'm good; post!

**Comment by dhuppenkothen** [comment]
Going to close this.
